### ISSUE TITLE
Could not deserialise string ["..."] into an image cropper value

### ISSUE THREAD

**Issue by jacksorjacksor** [prjseal/Clean-Starter-Kit-for-Umbraco-v9#16]
Morning!

First time I access a page on a fresh CSK project I got the below log. Seems to happen the first time I go to a new page, then I'm guessing the image gets cached and all's well. The images still load as expected and all seems to run fine, just wanted to highlight that error message.

Umbraco: 10.6.1
CSK: 3.0.1
DB connection: Azure SQL

```
 Could not deserialize string '/media/f01jqvmq/bluetooth-white-keyboard.jpg' into an image cropper value.
Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got m. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValueConverter.ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, Object source, Boolean preview)
[08:22:17 INF] Sending image. Request uri: 'http://localhost:3946/media/f01jqvmq/bluetooth-white-keyboard.jpg?width=1903&height=628&rnd=133356966439170000'. Cached Key: '7f2fd81681b5'
[08:22:35 INF] Sending image. Request uri: 'https://localhost:44303/media/f01jqvmq/bluetooth-white-keyboard.jpg?width=1903&height=628&rnd=133356966439170000'. Cached Key: '7f2fd81681b5'
```

**Comment by prjseal** [comment]
Hi Richard

Thanks for reporting this. I see this error too on different sites not just this starter kit. There doesn't seem to be anything actually broken and it just seems to be noise from image sharp. 

Is the rest of the starter kit ok for you?

Paul

**Comment by jacksorjacksor** [comment]
Hi Paul,

Ah fair! Will close, just wanted to make you aware.

Yeah the rest of everything's running just fine so far, or at least the issues are at my end (i.e. need to use blob storage to store the images/media).

Cheers!

Rich
